name: ExtraCrates
main: com.extracrates.ExtraCratesPlugin
version: 1.0.0
api-version: 1.20
softdepend:
  - Vault
commands:
  crate:
    description: Comandos principales de ExtraCrates
    usage: /<command> <gui|open|preview|reload|givekey|route>
permissions:
  extracrates.gui:
    default: true
  extracrates.open:
    default: true
  extracrates.preview:
    default: true
  extracrates.reload:
    default: op
  extracrates.givekey:
    default: op
  extracrates.route.editor:
    default: op
