name: ExtraCrates
main: com.extracrates.ExtraCratesPlugin
version: ${project.version}
description: Base scaffolding for a complex crates plugin.
author: Savaduki
api-version: '1.21'
softdepend: [ProtocolLib]
commands:
  crate:
    description: Manage crates and their main options.
    usage: /<command> <gui|open|preview|cutscene|reload|givekey|route|sync|migrate>
permissions:
  extracrates.gui:
    description: Allows opening the crates GUI.
    default: true
  extracrates.history:
    description: Allows viewing open history.
    default: true
  extracrates.open:
    description: Allows opening crates.
    default: true
  extracrates.preview:
    description: Allows previewing crates.
    default: true
  extracrates.reroll:
    description: Allows rerolling crate rewards.
    default: true
  extracrates.reload:
    description: Allows reloading crate configuration.
    default: op
  extracrates.givekey:
    description: Allows giving crate keys.
    default: op
  extracrates.route.editor:
    description: Allows editing cutscene paths for crates.
    default: op
  extracrates.sync:
    description: Allows managing crate synchronization.
    default: op
  extracrates.migrate:
    description: Allows migrating data between storages.
    default: op
  extracrates.crate.edit:
    description: Allows editing crates via command.
    default: op
  extracrates.crate.delete:
    description: Allows deleting crates via command.
    default: op
  extracrates.pool.create:
    description: Allows creating pools via command.
    default: op
  extracrates.pool.edit:
    description: Allows editing pools via command.
    default: op
  extracrates.pool.delete:
    description: Allows deleting pools via command.
    default: op
  extracrates.reward.create:
    description: Allows creating rewards via command.
    default: op
  extracrates.reward.edit:
    description: Allows editing rewards via command.
    default: op
  extracrates.reward.delete:
    description: Allows deleting rewards via command.
    default: op
  extracrates.reward.give:
    description: Allows manually giving rewards.
    default: op
  extracrates.reward.claim:
    description: Allows claiming pending rewards.
    default: true
